sudo: false
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r install/requirements.txt
  - pip install nose2
  - pip install nose2[coverage_plugin]>=0.6.5
  - pip install codecov
# command to run tests
script: nose2 -v

# Push the results back to codecov
after_success:
  - codecov

notifications:
  slack: revolution-robotics:sXlaetqFuXuT3Vr4atwogEdK
