language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  # PyPy versions
  - "pypy3.5"
  - "pypy3.6"
  - "pypy3.7"
# command to install dependencies
install:
  - pip install -r install/requirements.txt
# command to run tests
script: python -m unittest discover -s tests
