language: python
python:
  - "3.5"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r install/requirements.txt
  - pip install .
# command to run tests
script: python -m unittest discover -s tests
